LLVM_ARGS=`llvm-config --cxxflags --ldflags --libs  --system-libs` 
CC=g++-7 ${LLVM_ARGS} -std=c++17 -pthread

RHYTHM_SOURCES=main.cpp tokens.cpp parser.cpp parse_tree.cpp ir_emitter.cpp
RHYTHM_OBJS=${RHYTHM_SOURCES:.cpp=.o}

all: rhythmc

# remove source and header files generated by yacc and lex
clean:
	rm parser.cpp parser.hpp tokens.cpp parser.output rhythmc *.o

force: clean all

parser.cpp: parser.y
	bison -dv -o $@ $^
	
parser.hpp: parser.o

tokens.cpp: tokens.l parser.hpp
	lex -o $@ $^

# suppress warnings from lex generated code
tokens.o: tokens.cpp
	${CC} -c $< -Wno-sign-compare -Wno-unused-function
# Generic rules for compiling a source file to an object file
%.o: %.cpp
	${CC} -c $<

rhythmc: ${RHYTHM_OBJS}
	g++-7 -o $@ ${RHYTHM_OBJS} -g3 ${LLVM_ARGS} -std=c++17 -pthread