LLVM_ARGS=`llvm-config --cxxflags --ldflags --libs  --system-libs` 
CC=g++-7 ${LLVM_ARGS} -std=c++17 -pthread
all: rhythmc

# remove source and header files generated by yacc and lex
clean:
	rm parser.cpp parser.hpp tokens.cpp parser.output rhythmc *.o

force: clean all

parser.cpp: parser.y
	bison -dv -o $@ $^
	
parser.hpp: parser.o

tokens.cpp: tokens.l parser.hpp
	lex -o $@ $^

# suppress warnings from lex generated code
tokens.o: tokens.cpp
	${CC} -c $< -Wno-sign-compare -Wno-unused-function
# Generic rules for compiling a source file to an object file
%.o: %.cpp
	${CC} -c $<

rhythmc: parser.o tokens.o
	g++-7 -o $@ main.cpp code_gen.cpp *.o -g3 ${LLVM_ARGS} -std=c++17 -pthread